### ISSUE TITLE
Change the default blog theme

### ISSUE THREAD

**Issue by calvin1978** [f5f6/f5f6.github.io#1]
默认的模板，在日志与日志间的间隔不分明， H2的字体比H1的字体还大等等。

想要漂亮， 又不能黑咕隆咚，豆瓣小清新风格有么？

**Comment by aleung** [comment]
请大家看看喜欢那种风格的 theme。我们不一定要照搬，可以从不同 theme 里面吸取不同的元素，但先定个总体风格。

这是 github 里面比较热门的一些：
- https://mmistakes.github.io/minimal-mistakes/
- http://lanyon.getpoole.com/
- https://mmistakes.github.io/hpstr-jekyll-theme/
- http://ironsummitmedia.github.io/startbootstrap-blog-home/

这里有一大堆： http://jekyllthemes.org/

**Comment by calvin1978** [comment]
http://ironsummitmedia.github.io/startbootstrap-blog-home/# 

好像最简单又符合我们的几个需求， 其他的可以慢慢再找。

不过右边的sidebar可以窄一点。

**Comment by aleung** [comment]
那就以 bootstrap 为基调吧。这个是 bootstrap + material design: http://torre.me.uk/jekyll-material-design/

**Comment by calvin1978** [comment]
加上material design的确更好看。

 就是那个google API fonts 要手工copy paste下来replace掉。

**Comment by aleung** [comment]
在 http://lanyon.getpoole.com/ 的基础上修改了。

**Comment by duffqiu** [comment]
文件间区分依然不是很明显，标题用黑体加粗？

**Comment by calvinxiu** [comment]
在手机上看分得挺清楚了，在Web上还是有点点不清晰，像昨晚那样，在文章底部拉条线出来？

**Comment by calvin1978** [comment]
文章标题已经有个灰色底了，理论上足够区分了，但这个灰色底好像浅了点，特别在笔记本上，所以不明显。

**Comment by aleung** [comment]
在我家的显示器上看，那个背景已经是比较明显了，我还专门改淡了。用公司显示器一看，果然是很浅。我把它改深色些吧。

**Comment by calvin1978** [comment]
已把标题们都改为我最喜欢的微软雅黑

**Comment by calvin1978** [comment]
日志间的间隔好像太宽了，每篇日志后貌似不用留白这么多。

**Comment by aleung** [comment]
界面基本 ok，必须的都齐备了，暂不再花时间纠结细节问题了。

**Comment by aleung** [comment]
界面基本 ok，必须的都齐备了，暂不再花时间纠结细节问题了。
