### ISSUE TITLE
建议去掉jekyll的window的程序

### ISSUE THREAD

**Issue by duffqiu** [f5f6/f5f6.github.io#11]
在需要vpn下载site的时候造成很慢

**Comment by aleung** [comment]
7.5M，就是在第一次 clone 的时候需要传输而已。

**Comment by cutemic** [comment]
不懂啊。其實放一個 URL 就行了吧？為什麼要把 binary 放上去？

**Comment by aleung** [comment]
@cutemic 是个办法。存放在哪里比较好呢？Github不再提供放download的地方了。

**Comment by cutemic** [comment]
@aleung how about this one: https://github.com/nilliams/jekyll.exe

**Comment by cutemic** [comment]
@aleung http://www.nickw.it/jekyll-dot-exe/

**Comment by calvin1978** [comment]
百度云.....

**Comment by aleung** [comment]
算啦，反正都已经放进去了，即使删除clone的时候还是会传输的，除非将历史版本truncate掉。
