### ISSUE TITLE
周刊在主页的现实会被其它新进的blog挪到后面

### ISSUE THREAD

**Issue by duffqiu** [f5f6/f5f6.github.io#12]
有没有办法将周刊的blog置顶？

**Comment by aleung** [comment]
修改 front matter 中的 date，改成最新日期。文件名不用改。http://jekyllrb.com/docs/frontmatter/

**Comment by duffqiu** [comment]
那就每次生成weekly post的时候直接将date设置成要发布的那个日期，而不是生成的日期，这样当周新增的post就不会跑到前面去
