### ISSUE TITLE
日志列表只显示摘要

### ISSUE THREAD

**Issue by calvin1978** [f5f6/f5f6.github.io#3]

**Comment by aleung** [comment]
但我不太喜欢只显示摘要这种模式。
Blog 本来就是按时间更新的，每次打开一个 blog site 不就是想看看最新的内容吗？读了一段之后发现还要再点击一下才能看全文，看完还得回退，这个动作太打断阅读流畅性了。
新闻网站那类更新非常频繁，文章多得读者读不完的才有这样的必要在列表中只显示摘要。

**Comment by calvin1978** [comment]
嗯， 可能是Template还不美观，东西一多就乱，造成想只看摘要，不想让主页太多内容， 等换了模板看看吧。
