### ISSUE TITLE
显示作者的URL

### ISSUE THREAD

**Issue by calvin1978** [f5f6/f5f6.github.io#4]
修改config.yml，注册用户的url信息

**Comment by aleung** [comment]
点击用户名，给出一个用户页面，包括用户信息和他的所有帖子，这样会比直接跳离本站到用户个人网站要友好些。

**Comment by calvin1978** [comment]
jkyll可编程到这个程度么？能行当然好。

**Comment by calvinxiu** [comment]
貌似不可能，关掉算了。

**Comment by calvinxiu** [comment]
好像用Where Filter可以，重开。
