### ISSUE TITLE
增加一篇文章指导大家如何在windows/linus下修改的指导?

### ISSUE THREAD

**Issue by duffqiu** [f5f6/f5f6.github.io#5]

**Comment by calvin1978** [comment]
第一篇文章还不够么，你润色一下？

**Comment by duffqiu** [comment]
好像没有说明如何搭建一个环境出来写github的blog. Leo用的是jelly，我还没用过。我之前用的是octopress，这个倒是有详细的介绍

**Comment by calvin1978** [comment]
下面这段还不够聪明的程序员们操作么？ 要么在"Help"里也说一下。

发表新日志

在 _posts 目录里新建一个文件， 遵循YYYY-MM-DD-name-of-post.markdown的命名规则， 并参考其他日志， 在正文最开始处放置正确的头信息。

然后用Git将文件提交。

**Comment by calvin1978** [comment]
你是指建一个 个人blog么？

**Comment by aleung** [comment]
更新了[Help](http://f5f6.github.io/help.html)，提供了Jekyll.exe，方便Windows用户。

**Comment by aclisp** [comment]
关于建一个 _个人blog_ 我是根据官方文档的指引：
1. 看完 https://pages.github.com/ (只有一点点内容)
2. 翻到最底下，看完 Blogging with Jekyll (
https://help.github.com/articles/using-jekyll-with-pages/)
3. 2里面的步骤其实有点小错误，当时我参考http://jekyllrb.com/的quick start guide搞定
4. Windows里下装ruby和bundler有点麻烦，可以参考
http://blog.florianwolters.de/educational/2014/04/18/Running_Jekyll_with_GitHub_Pages_using_Windows_8.1_x64_and_Ruby_2.0_x64/
(我没有试过)
5. ruby的源 https://rubygems.org被墙了，导致更新不到 github-pages 最新包。可以换成淘宝镜像
ruby.taobao.org

**Comment by aleung** [comment]
怎样在Windows下安装Jekyll我可以写一下，前后重装机器已经装了好几次了 :)

@aclisp 安装gem如果是SSL错误的话，不是墙的问题，而是因为证书变了，有解决方法。

**Comment by duffqiu** [comment]
@aleung ,我在第一周的周刊里留了个空白的link给你写jekyll

**Comment by calvin1978** [comment]
@aleung ,@duffqiu  已移到一篇独立的日志。

**Comment by cutemic** [comment]
簡單文字修改的話我都是參考周刊頁面上的在線編輯連接，直接在線編輯和預覽 markdown 文件：
https://github.com/f5f6/f5f6.github.io/edit/master/_posts/2015-01-11-weekly-1.markdown

**Comment by duffqiu** [comment]
linux下可以用gedit编辑markdown，支持markdown语法。不过需要安装python的markdown包以及安装https://github.com/jpfleury/gedit-markdown
不过中间需要费点周折整一下pytyon的版本和对应没有安装的依赖包

装好后用gedit就可以直接编写markdown有高亮同时有preview
