### ISSUE TITLE
Related Posts现在的逻辑是啥?

### ISSUE THREAD

**Issue by calvin1978** [f5f6/f5f6.github.io#7]
好像没什么逻辑，最好是按同分类或同Tag

**Comment by aleung** [comment]
这个要有tag才有用。没有tag的时候等于是同一时间前后的post。
参考：http://zhangwenli.com/blog/2014/07/15/jekyll-related-posts-without-plugin/

**Comment by calvin1978** [comment]
在wordpress里，没tag就不显示related blog了，是不是可以参考下？ 现在同一时间前后的blog其实没什么related。

**Comment by calvin1978** [comment]
看了下代码，用site.related_posts 这个变量，没法改的。
