### ISSUE TITLE
周刊的标题太普通

### ISSUE THREAD

**Issue by duffqiu** [f5f6/f5f6.github.io#8]
我们需要一个大气或“另类”的标题。
需要一个logo，不知道ux能否帮个忙

**Comment by duffqiu** [comment]
我的建议：

两楼周刊
56周刊

**Comment by duffqiu** [comment]
怎么又关又开issue?

**Comment by duffqiu** [comment]
另外一个名字：蓝色天堂(为什么是蓝色你懂的， 大堂不够雅，改用天堂)
Leo建议:  大堂
Mic建议： 楼上楼下
Calvin: 六楼后座

**Comment by emilzhang** [comment]
肠厂Weekly

**Comment by calvin1978** [comment]
就叫五楼六楼算了。六楼后座是Beyond的乐房。

**Comment by calvin1978** [comment]
可以close了没？
